server:
  servlet:
    context-path: /stuffs
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muduo_cloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql_5_7

logging:
    level:
      org:
        jooq: debug