server:
  port: 9093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muduo_cloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql_5_7

  cache:
    type: redis

  data:
    mongodb:
      host: localhost
      port: 27017
      database: muduo

  activemq:
    broker-url: tcp://localhost:61616?jms.useAsyncSend=true

logging:
    level:
      org:
        jooq: debug