/*
 * This file is generated by jOOQ.
*/
package cn.edu.bnuz.jooq.tables.records;


import cn.edu.bnuz.jooq.tables.Account;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = -1778883402;

    /**
     * Setter for <code>muduo_cloud.account.number</code>. 账号
     */
    public void setNumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>muduo_cloud.account.number</code>. 账号
     */
    public String getNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>muduo_cloud.account.password</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>muduo_cloud.account.password</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>muduo_cloud.account.name</code>. 姓名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>muduo_cloud.account.name</code>. 姓名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>muduo_cloud.account.identity</code>. 身份
     */
    public void setIdentity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>muduo_cloud.account.identity</code>. 身份
     */
    public String getIdentity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>muduo_cloud.account.lbl_xy</code>. 学院
     */
    public void setLblXy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>muduo_cloud.account.lbl_xy</code>. 学院
     */
    public String getLblXy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>muduo_cloud.account.lbl_xzb</code>. 行政班
     */
    public void setLblXzb(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>muduo_cloud.account.lbl_xzb</code>. 行政班
     */
    public String getLblXzb() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Account.ACCOUNT.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Account.ACCOUNT.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Account.ACCOUNT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Account.ACCOUNT.IDENTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Account.ACCOUNT.LBL_XY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Account.ACCOUNT.LBL_XZB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIdentity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLblXy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLblXzb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdentity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLblXy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLblXzb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecord value1(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecord value4(String value) {
        setIdentity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecord value5(String value) {
        setLblXy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecord value6(String value) {
        setLblXzb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(String number, String password, String name, String identity, String lblXy, String lblXzb) {
        super(Account.ACCOUNT);

        set(0, number);
        set(1, password);
        set(2, name);
        set(3, identity);
        set(4, lblXy);
        set(5, lblXzb);
    }
}
