/*
 * This file is generated by jOOQ.
*/
package cn.edu.bnuz.jooq.tables.records;


import cn.edu.bnuz.jooq.tables.ClassroomApply;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassroomApplyRecord extends UpdatableRecordImpl<ClassroomApplyRecord> implements Record8<Integer, String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1241514754;

    /**
     * Setter for <code>muduo_cloud.classroom_apply.id</code>. 教室申请表Id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.id</code>. 教室申请表Id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>muduo_cloud.classroom_apply.number</code>. 申请人
     */
    public void setNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.number</code>. 申请人
     */
    public String getNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>muduo_cloud.classroom_apply.day</code>. 申请的那一天
     */
    public void setDay(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.day</code>. 申请的那一天
     */
    public String getDay() {
        return (String) get(2);
    }

    /**
     * Setter for <code>muduo_cloud.classroom_apply.time</code>. 申请的那几节课
     */
    public void setTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.time</code>. 申请的那几节课
     */
    public String getTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>muduo_cloud.classroom_apply.classroom</code>. 申请的哪间教室
     */
    public void setClassroom(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.classroom</code>. 申请的哪间教室
     */
    public String getClassroom() {
        return (String) get(4);
    }

    /**
     * Setter for <code>muduo_cloud.classroom_apply.reason</code>. 申请的原因
     */
    public void setReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.reason</code>. 申请的原因
     */
    public String getReason() {
        return (String) get(5);
    }

    /**
     * Setter for <code>muduo_cloud.classroom_apply.status</code>. 申请单的状态(applying-&gt;申请中, applied-&gt;已统一,refuse-&gt;拒绝)
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.status</code>. 申请单的状态(applying-&gt;申请中, applied-&gt;已统一,refuse-&gt;拒绝)
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>muduo_cloud.classroom_apply.create_time</code>. 申请的时间
     */
    public void setCreateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>muduo_cloud.classroom_apply.create_time</code>. 申请的时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ClassroomApply.CLASSROOM_APPLY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ClassroomApply.CLASSROOM_APPLY.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ClassroomApply.CLASSROOM_APPLY.DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ClassroomApply.CLASSROOM_APPLY.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ClassroomApply.CLASSROOM_APPLY.CLASSROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ClassroomApply.CLASSROOM_APPLY.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ClassroomApply.CLASSROOM_APPLY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ClassroomApply.CLASSROOM_APPLY.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getClassroom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getClassroom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value2(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value3(String value) {
        setDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value4(String value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value5(String value) {
        setClassroom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value6(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord value8(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassroomApplyRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassroomApplyRecord
     */
    public ClassroomApplyRecord() {
        super(ClassroomApply.CLASSROOM_APPLY);
    }

    /**
     * Create a detached, initialised ClassroomApplyRecord
     */
    public ClassroomApplyRecord(Integer id, String number, String day, String time, String classroom, String reason, String status, Timestamp createTime) {
        super(ClassroomApply.CLASSROOM_APPLY);

        set(0, id);
        set(1, number);
        set(2, day);
        set(3, time);
        set(4, classroom);
        set(5, reason);
        set(6, status);
        set(7, createTime);
    }
}
