/*
 * This file is generated by jOOQ.
*/
package cn.edu.bnuz.jooq.tables.records;


import cn.edu.bnuz.jooq.tables.Maintain;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaintainRecord extends UpdatableRecordImpl<MaintainRecord> implements Record9<Integer, String, String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1403645613;

    /**
     * Setter for <code>muduo_cloud.maintain.maintain_id</code>. 维护表id
     */
    public void setMaintainId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.maintain_id</code>. 维护表id
     */
    public Integer getMaintainId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.report_number</code>. 维护人
     */
    public void setReportNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.report_number</code>. 维护人
     */
    public String getReportNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.repair_number</code>.
     */
    public void setRepairNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.repair_number</code>.
     */
    public String getRepairNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.type</code>. 设备单的状态(report-&gt;报修、maintain-&gt;维护)
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.type</code>. 设备单的状态(report-&gt;报修、maintain-&gt;维护)
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.status</code>. 设备单的状态(repairing-&gt;维修中、repaired-&gt;维修完成)
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.status</code>. 设备单的状态(repairing-&gt;维修中、repaired-&gt;维修完成)
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.classroom</code>. 维护的教室
     */
    public void setClassroom(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.classroom</code>. 维护的教室
     */
    public String getClassroom() {
        return (String) get(5);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.description</code>. 维护描述
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.description</code>. 维护描述
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.images</code>. 图片链接
     */
    public void setImages(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.images</code>. 图片链接
     */
    public String getImages() {
        return (String) get(7);
    }

    /**
     * Setter for <code>muduo_cloud.maintain.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>muduo_cloud.maintain.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Maintain.MAINTAIN.MAINTAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Maintain.MAINTAIN.REPORT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Maintain.MAINTAIN.REPAIR_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Maintain.MAINTAIN.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Maintain.MAINTAIN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Maintain.MAINTAIN.CLASSROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Maintain.MAINTAIN.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Maintain.MAINTAIN.IMAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Maintain.MAINTAIN.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMaintainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReportNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRepairNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getClassroom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getImages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMaintainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReportNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRepairNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getClassroom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getImages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value1(Integer value) {
        setMaintainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value2(String value) {
        setReportNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value3(String value) {
        setRepairNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value6(String value) {
        setClassroom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value8(String value) {
        setImages(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord value9(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaintainRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MaintainRecord
     */
    public MaintainRecord() {
        super(Maintain.MAINTAIN);
    }

    /**
     * Create a detached, initialised MaintainRecord
     */
    public MaintainRecord(Integer maintainId, String reportNumber, String repairNumber, String type, String status, String classroom, String description, String images, Timestamp updateTime) {
        super(Maintain.MAINTAIN);

        set(0, maintainId);
        set(1, reportNumber);
        set(2, repairNumber);
        set(3, type);
        set(4, status);
        set(5, classroom);
        set(6, description);
        set(7, images);
        set(8, updateTime);
    }
}
