/*
 * This file is generated by jOOQ.
*/
package cn.edu.bnuz.jooq.tables.records;


import cn.edu.bnuz.jooq.tables.Stuff;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StuffRecord extends UpdatableRecordImpl<StuffRecord> implements Record7<Integer, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1736238982;

    /**
     * Setter for <code>muduo_cloud.stuff.stuff_id</code>. 失物找寻表的id
     */
    public void setStuffId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>muduo_cloud.stuff.stuff_id</code>. 失物找寻表的id
     */
    public Integer getStuffId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>muduo_cloud.stuff.number</code>. 发布人的账号
     */
    public void setNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>muduo_cloud.stuff.number</code>. 发布人的账号
     */
    public String getNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>muduo_cloud.stuff.type</code>. loss(丢失自己的物品)、stick(捡到别人的物品)
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>muduo_cloud.stuff.type</code>. loss(丢失自己的物品)、stick(捡到别人的物品)
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>muduo_cloud.stuff.phone</code>. 发布人留下的联系方式
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>muduo_cloud.stuff.phone</code>. 发布人留下的联系方式
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>muduo_cloud.stuff.description</code>. 物品的简单描述
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>muduo_cloud.stuff.description</code>. 物品的简单描述
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>muduo_cloud.stuff.images</code>. 图片的json格式存储
     */
    public void setImages(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>muduo_cloud.stuff.images</code>. 图片的json格式存储
     */
    public String getImages() {
        return (String) get(5);
    }

    /**
     * Setter for <code>muduo_cloud.stuff.create_time</code>. 发布的时间
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>muduo_cloud.stuff.create_time</code>. 发布的时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Stuff.STUFF.STUFF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Stuff.STUFF.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Stuff.STUFF.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Stuff.STUFF.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Stuff.STUFF.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Stuff.STUFF.IMAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Stuff.STUFF.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStuffId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getImages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStuffId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getImages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord value1(Integer value) {
        setStuffId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord value2(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord value6(String value) {
        setImages(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StuffRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StuffRecord
     */
    public StuffRecord() {
        super(Stuff.STUFF);
    }

    /**
     * Create a detached, initialised StuffRecord
     */
    public StuffRecord(Integer stuffId, String number, String type, String phone, String description, String images, Timestamp createTime) {
        super(Stuff.STUFF);

        set(0, stuffId);
        set(1, number);
        set(2, type);
        set(3, phone);
        set(4, description);
        set(5, images);
        set(6, createTime);
    }
}
