server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muduo_cloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver