/*
 * This file is generated by jOOQ.
*/
package cn.edu.bnuz.jooq;


import cn.edu.bnuz.jooq.tables.Account;
import cn.edu.bnuz.jooq.tables.Authority;
import cn.edu.bnuz.jooq.tables.ClassroomApply;
import cn.edu.bnuz.jooq.tables.Maintain;
import cn.edu.bnuz.jooq.tables.Session;
import cn.edu.bnuz.jooq.tables.Stuff;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>muduo_cloud</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PRIMARY = Indexes0.ACCOUNT_PRIMARY;
    public static final Index AUTHORITY_PRIMARY = Indexes0.AUTHORITY_PRIMARY;
    public static final Index CLASSROOM_APPLY_PRIMARY = Indexes0.CLASSROOM_APPLY_PRIMARY;
    public static final Index MAINTAIN_PRIMARY = Indexes0.MAINTAIN_PRIMARY;
    public static final Index SESSION_PRIMARY = Indexes0.SESSION_PRIMARY;
    public static final Index STUFF_PRIMARY = Indexes0.STUFF_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PRIMARY = Internal.createIndex("PRIMARY", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.NUMBER }, true);
        public static Index AUTHORITY_PRIMARY = Internal.createIndex("PRIMARY", Authority.AUTHORITY, new OrderField[] { Authority.AUTHORITY.NUMBER, Authority.AUTHORITY.AUTHORITY_ }, true);
        public static Index CLASSROOM_APPLY_PRIMARY = Internal.createIndex("PRIMARY", ClassroomApply.CLASSROOM_APPLY, new OrderField[] { ClassroomApply.CLASSROOM_APPLY.ID }, true);
        public static Index MAINTAIN_PRIMARY = Internal.createIndex("PRIMARY", Maintain.MAINTAIN, new OrderField[] { Maintain.MAINTAIN.MAINTAIN_ID }, true);
        public static Index SESSION_PRIMARY = Internal.createIndex("PRIMARY", Session.SESSION, new OrderField[] { Session.SESSION.OPENID }, true);
        public static Index STUFF_PRIMARY = Internal.createIndex("PRIMARY", Stuff.STUFF, new OrderField[] { Stuff.STUFF.STUFF_ID }, true);
    }
}
