/*
 * This file is generated by jOOQ.
*/
package cn.edu.bnuz.jooq;


import cn.edu.bnuz.jooq.tables.Account;
import cn.edu.bnuz.jooq.tables.Authority;
import cn.edu.bnuz.jooq.tables.ClassroomApply;
import cn.edu.bnuz.jooq.tables.Maintain;
import cn.edu.bnuz.jooq.tables.Session;
import cn.edu.bnuz.jooq.tables.Stuff;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MuduoCloud extends SchemaImpl {

    private static final long serialVersionUID = 2031757070;

    /**
     * The reference instance of <code>muduo_cloud</code>
     */
    public static final MuduoCloud MUDUO_CLOUD = new MuduoCloud();

    /**
     * The table <code>muduo_cloud.account</code>.
     */
    public final Account ACCOUNT = cn.edu.bnuz.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>muduo_cloud.authority</code>.
     */
    public final Authority AUTHORITY = cn.edu.bnuz.jooq.tables.Authority.AUTHORITY;

    /**
     * The table <code>muduo_cloud.classroom_apply</code>.
     */
    public final ClassroomApply CLASSROOM_APPLY = cn.edu.bnuz.jooq.tables.ClassroomApply.CLASSROOM_APPLY;

    /**
     * The table <code>muduo_cloud.maintain</code>.
     */
    public final Maintain MAINTAIN = cn.edu.bnuz.jooq.tables.Maintain.MAINTAIN;

    /**
     * The table <code>muduo_cloud.session</code>.
     */
    public final Session SESSION = cn.edu.bnuz.jooq.tables.Session.SESSION;

    /**
     * The table <code>muduo_cloud.stuff</code>.
     */
    public final Stuff STUFF = cn.edu.bnuz.jooq.tables.Stuff.STUFF;

    /**
     * No further instances allowed
     */
    private MuduoCloud() {
        super("muduo_cloud", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Authority.AUTHORITY,
            ClassroomApply.CLASSROOM_APPLY,
            Maintain.MAINTAIN,
            Session.SESSION,
            Stuff.STUFF);
    }
}
