/*
 * This file is generated by jOOQ.
*/
package cn.edu.bnuz.jooq;


import cn.edu.bnuz.jooq.tables.Account;
import cn.edu.bnuz.jooq.tables.Authority;
import cn.edu.bnuz.jooq.tables.ClassroomApply;
import cn.edu.bnuz.jooq.tables.Maintain;
import cn.edu.bnuz.jooq.tables.Session;
import cn.edu.bnuz.jooq.tables.Stuff;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in muduo_cloud
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>muduo_cloud.account</code>.
     */
    public static final Account ACCOUNT = cn.edu.bnuz.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>muduo_cloud.authority</code>.
     */
    public static final Authority AUTHORITY = cn.edu.bnuz.jooq.tables.Authority.AUTHORITY;

    /**
     * The table <code>muduo_cloud.classroom_apply</code>.
     */
    public static final ClassroomApply CLASSROOM_APPLY = cn.edu.bnuz.jooq.tables.ClassroomApply.CLASSROOM_APPLY;

    /**
     * The table <code>muduo_cloud.maintain</code>.
     */
    public static final Maintain MAINTAIN = cn.edu.bnuz.jooq.tables.Maintain.MAINTAIN;

    /**
     * The table <code>muduo_cloud.session</code>.
     */
    public static final Session SESSION = cn.edu.bnuz.jooq.tables.Session.SESSION;

    /**
     * The table <code>muduo_cloud.stuff</code>.
     */
    public static final Stuff STUFF = cn.edu.bnuz.jooq.tables.Stuff.STUFF;
}
